In [28]:
import numpy as np

v = np.array([1, 1, 1])
A = np.eye(3) - 0.01 * v * v.T

def f(x):
    return np.dot(x, np.dot(A, x)) * 0.5

print(A)

def hessian(f, x, h=1e-5):
    I = np.eye(len(x))
    H = np.zeros((len(x), len(x)))
    for i in range(len(x)):
        for j in range(len(x)):
            for p in [-h, h]:
                for q in [-h, h]:
                    H[i, j] += f(x + p * I[i] + q * I[j]) / (2*2*p*q)
    return H


def hessian_rand(f, x, h=1e-5, N=10):
    w = np.random.standard_normal((len(x), N))
    v = np.random.standard_normal((len(x), N))
    u = np.zeros(N)
    for i in range(N):
        for p in [-h, h]:
            for q in [-h, h]:
                u[i] += f(x + p * w[:, i] + q * v[:, i]) / (4*p*q)
    wv_flat = (w[:, None, :] * v[None, :, :]).reshape(len(x)*len(x), N).T
    H_flat = np.reshape(np.linalg.solve(wv_flat.T @ wv_flat, wv_flat.T @ u), (len(x), len(x)))
    return H_flat
    
    
    

print(hessian(f, np.array([1, 1, 1]), h=1e-1))
print(hessian_rand(f, np.array([1, 1, 1]), h=1e-1, N=10))

[[ 0.99 -0.01 -0.01]
 [-0.01  0.99 -0.01]
 [-0.01 -0.01  0.99]]
[[ 0.99 -0.01 -0.01]
 [-0.01  0.99 -0.01]
 [-0.01 -0.01  0.99]]
[[ 0.99 -0.01 -0.01]
 [-0.01  0.99 -0.01]
 [-0.01 -0.01  0.99]]
